### PR TITLE
Avoid unnecessary type convertion

### PR DESCRIPTION
**Pull request by ccoVeille**
- **fix comments**
- **avoid type juggling**

### CODE REVIEW

**Comment by orsinium** [comment]
thanks!

**Comment by ccoVeille** [comment]
BTW, could you enable issues and discussions on your repository ?

I have no other way to reach you about this project and discussion about implementation

Unless you are on Slack Gopher, maybe?

**Comment by orsinium** [comment]
Sorry, I don't have capacity to moderate discussions about the project. It is provided as-is, see LICENSE.

**Comment by ccoVeille** [comment]
I'm unsure I have understand what you meant.

So, let me ask again by rephrasing:

Could you enable the "Issues" feature on GitHub for this project?

**Pull request merged**
